apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: youtube_clone
  name: youtube
spec:
  replicas: 4
  selector:
    matchLabels:
      app: youtube_clone
  template:
    metadata:
      labels:
        app: youtube_clone
    spec:
      containers:
      - name: cont1
        image: abishnu08/youtube:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: youtube_clone
  ports:
    - port: 80
      targetPort: 80
